name: Auto Increment Tag

on:
  push:
    branches:
      - main
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: rwickit/action-auto-tag@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}